# Generated by Django 4.2.2 on 2023-07-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuposition_menu_sub_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuposition',
            name='menu_item',
        ),
    ]
