# Generated by Django 4.2.2 on 2023-07-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menuposition_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='menu_sub_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menusubitems', to='menu.menusubitems'),
        ),
        migrations.AlterField(
            model_name='menusubitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='menu.menuitem'),
        ),
    ]
