# Generated by Django 4.2.2 on 2023-07-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuposition_menu_sub_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuposition',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menuitems_positions', to='menu.menuitem'),
            preserve_default=False,
        ),
    ]
