# Generated by Django 4.2.2 on 2023-07-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuposition_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
