# Generated by Django 4.2.2 on 2023-07-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuposition_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
